services:
  web:
    build: .
    container_name: docsign_web_app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5176:5176"
    environment:
      NODE_ENV: development
    command: pnpm dev --host 0.0.0.0 --port 5176
